import React, { useState, useEffect } from 'react';
import { 
  CheckCircle2, AlertTriangle, Clock, PhoneCall, Truck, 
  ArrowRight, ShieldAlert, Calendar, RefreshCw, Layers, PlusCircle,
  Copy, Check, Share2, Building2, MapPin, Package, ArrowUpRight, ArrowDownLeft,
  ChevronRight, Sparkles
} from 'lucide-react';
import { fetchDailyTasks, fetchLogisticsPlan } from '../api';

export default function DailyTasksView({ onOpenFollowup, onAdvanceStage, onOpenBulkDispatch }) {
  const [tasks, setTasks] = useState(null);
  const [logisticsPlan, setLogisticsPlan] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activePlanTab, setActivePlanTab] = useState('TRIP'); // 'TRIP' or 'LOCAL'
  
  // Calculate tomorrow's date for default Day-Before Planning
  const tomorrowStr = (() => {
    const d = new Date();
    d.setDate(d.getDate() + 1);
    return d.toISOString().split('T')[0];
  })();
  const todayStr = new Date().toISOString().split('T')[0];
  
  const [planDate, setPlanDate] = useState(tomorrowStr);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    loadAll();
  }, [planDate]);

  async function loadAll() {
    try {
      setLoading(true);
      const [tData, pData] = await Promise.all([
        fetchDailyTasks(),
        fetchLogisticsPlan(planDate)
      ]);
      setTasks(tData);
      setLogisticsPlan(pData);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  function handleCopyPlan() {
    if (!logisticsPlan) return;
    const isTrip = activePlanTab === 'TRIP';
    const plan = isTrip ? logisticsPlan.trip_plan : logisticsPlan.local_plan;
    const title = isTrip ? '🚚 TRIP LOGISTICS PLAN (Outstation Transport)' : '🛵 LOCAL LOGISTICS PLAN (Local Jobwork Movement)';
    
    let text = `==============================\n`;
    text += `${title}\n`;
    text += `📅 Target Planning Date: ${planDate} ${planDate === tomorrowStr ? '(Day-Before Plan for Tomorrow)' : ''}\n`;
    text += `==============================\n\n`;
    
    text += `📦 1. OUTWARD DISPATCHES (To Load & Send to Vendors):\n`;
    if (!plan?.outward_dispatches?.length) {
      text += `   - No outward materials scheduled for dispatch.\n`;
    } else {
      plan.outward_dispatches.forEach((item, idx) => {
        text += `   ${idx + 1}. [${item.item_code}] ${item.item_name}\n`;
        text += `      Qty: ${item.quantity} pcs | Est Weight: ${item.total_weight_kg || 0} kg\n`;
        text += `      Next Process: ${item.next_process || 'Outsourced'}\n`;
        text += `      Destination: ${item.destination_vendor_name || 'Vendor'} (${item.destination_vendor_phone || 'No phone'})\n`;
        if (item.destination_vendor_address) text += `      Address: ${item.destination_vendor_address}\n`;
      });
    }
    
    text += `\n📥 2. INWARD COLLECTIONS (To Collect / Expected From Vendors):\n`;
    if (!plan?.inward_pickups?.length) {
      text += `   - No inward collections expected.\n`;
    } else {
      plan.inward_pickups.forEach((item, idx) => {
        text += `   ${idx + 1}. [${item.item_code}] ${item.item_name}\n`;
        text += `      Qty: ${item.quantity} pcs | Est Weight: ${item.total_weight_kg || 0} kg\n`;
        text += `      Process: ${item.current_process}\n`;
        text += `      Vendor: ${item.vendor_name} (${item.vendor_phone || 'No phone'})\n`;
        if (item.challan_no) text += `      DC Ref: ${item.challan_no}\n`;
        text += `      Due Date: ${item.expected_delivery_date || 'N/A'}\n`;
      });
    }
    
    text += `\n📊 LOGISTICS SUMMARY:\n`;
    text += `- Outward Load: ${plan?.total_outward_qty || 0} pcs (${plan?.total_outward_weight_kg || 0} kg)\n`;
    text += `- Inward Collection: ${plan?.total_inward_qty || 0} pcs (${plan?.total_inward_weight_kg || 0} kg)\n`;
    text += `- Vendors Involved: ${plan?.vendors_count || 0}\n`;
    text += `==============================\n`;
    text += `Generated by Rajtamil Jobwork Engineer OS`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  const overdue = tasks?.overdue_tasks || [];
  const dueToday = tasks?.due_today_tasks || [];
  const inhouse = tasks?.inhouse_tasks || [];
  const recentFollowups = tasks?.recent_followups || [];

  const currentPlan = activePlanTab === 'TRIP' ? logisticsPlan?.trip_plan : logisticsPlan?.local_plan;
  const isTripActive = activePlanTab === 'TRIP';

  return (
    <div className="space-y-6">
      
      {/* ─── LOGISTICS PLANNING SECTION (TRIP PLAN & LOCAL PLAN) ─────────────────────────── */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-5">
        
        {/* Module Header & Target Planning Date */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-indigo-950/80 text-indigo-400 border border-indigo-700/60">
                <Truck className="w-4 h-4" />
              </span>
              <h2 className="text-base font-extrabold text-white tracking-wide">
                Day-Before Logistics Planning
              </h2>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-cyan-950 text-cyan-300 border border-cyan-700/60 uppercase">
                {planDate === tomorrowStr ? 'Planning for Tomorrow' : planDate === todayStr ? "Today's Execution" : `Plan: ${planDate}`}
              </span>
            </div>
            <p className="text-xs text-slate-400">
              Prepare Outward Dispatches and Inward Material Collections 1 day in advance for Trip vehicles and Local subcontract runs
            </p>
          </div>

          {/* Date Selector & Copy Plan */}
          <div className="flex items-center gap-2 flex-wrap">
            <div className="flex items-center bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
              <button
                type="button"
                onClick={() => setPlanDate(tomorrowStr)}
                className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                  planDate === tomorrowStr 
                    ? 'bg-indigo-600 text-white shadow-sm' 
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Tomorrow (Day-Before)
              </button>
              <button
                type="button"
                onClick={() => setPlanDate(todayStr)}
                className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                  planDate === todayStr 
                    ? 'bg-slate-800 text-white shadow-sm' 
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Today
              </button>
              <input
                type="date"
                value={planDate}
                onChange={(e) => setPlanDate(e.target.value)}
                className="bg-transparent text-slate-300 px-2 py-1 text-xs focus:outline-none font-mono"
              />
            </div>

            <button
              onClick={handleCopyPlan}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all shadow-sm cursor-pointer border ${
                copied
                  ? 'bg-emerald-950 text-emerald-300 border-emerald-500'
                  : 'bg-slate-950 hover:bg-slate-800 text-slate-200 border-slate-700 hover:border-slate-600'
              }`}
              title="Copy formatted plan for WhatsApp / Transport Driver"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Copied for WhatsApp!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Copy {isTripActive ? 'Trip' : 'Local'} Plan</span>
                </>
              )}
            </button>

            <button
              onClick={onOpenBulkDispatch}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold shadow-md shadow-indigo-600/30 transition-all cursor-pointer"
            >
              <Share2 className="w-3.5 h-3.5" />
              <span>Issue Dispatch DC</span>
            </button>

            <button
              onClick={loadAll}
              disabled={loading}
              className="p-1.5 rounded-xl bg-slate-950 hover:bg-slate-800 text-slate-400 hover:text-white border border-slate-800 transition-colors"
              title="Refresh Plan"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-cyan-400' : ''}`} />
            </button>
          </div>
        </div>

        {/* ─── Plan Type Switcher (Trip Plan vs Local Plan) ─── */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <button
            type="button"
            onClick={() => setActivePlanTab('TRIP')}
            className={`p-4 rounded-xl border text-left flex items-start justify-between gap-3 transition-all cursor-pointer ${
              isTripActive
                ? 'bg-amber-950/40 border-amber-500 shadow-md shadow-amber-950/30 ring-1 ring-amber-500/50'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 text-slate-400'
            }`}
          >
            <div className="flex items-start gap-3">
              <div className={`p-2 rounded-xl shrink-0 ${isTripActive ? 'bg-amber-600 text-white' : 'bg-slate-800 text-slate-400'}`}>
                <Truck className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className={`text-sm font-bold ${isTripActive ? 'text-white' : 'text-slate-300'}`}>
                    🚚 Trip Plan (Outstation Transport)
                  </h3>
                  {isTripActive && (
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-900/80 text-amber-300 border border-amber-700">
                      ACTIVE PLAN
                    </span>
                  )}
                </div>
                <p className="text-xs text-slate-400 mt-0.5">
                  Dedicated vehicle routes & outstation vendors requiring booking a day prior
                </p>
                <div className="flex items-center gap-3 mt-2 text-xs font-mono">
                  <span className="text-amber-300 font-semibold">
                    {logisticsPlan?.trip_plan?.total_outward_items || 0} to Send ({logisticsPlan?.trip_plan?.total_outward_qty || 0} pcs)
                  </span>
                  <span className="text-slate-600">•</span>
                  <span className="text-cyan-300 font-semibold">
                    {logisticsPlan?.trip_plan?.total_inward_items || 0} to Collect ({logisticsPlan?.trip_plan?.total_inward_qty || 0} pcs)
                  </span>
                </div>
              </div>
            </div>
            <div className="text-right shrink-0">
              <span className="text-xs font-mono font-bold text-amber-400 bg-amber-950 px-2 py-1 rounded border border-amber-800">
                {logisticsPlan?.trip_plan?.total_outward_weight_kg || 0} KG
              </span>
            </div>
          </button>

          <button
            type="button"
            onClick={() => setActivePlanTab('LOCAL')}
            className={`p-4 rounded-xl border text-left flex items-start justify-between gap-3 transition-all cursor-pointer ${
              !isTripActive
                ? 'bg-cyan-950/40 border-cyan-500 shadow-md shadow-cyan-950/30 ring-1 ring-cyan-500/50'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 text-slate-400'
            }`}
          >
            <div className="flex items-start gap-3">
              <div className={`p-2 rounded-xl shrink-0 ${!isTripActive ? 'bg-cyan-600 text-white' : 'bg-slate-800 text-slate-400'}`}>
                <Building2 className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className={`text-sm font-bold ${!isTripActive ? 'text-white' : 'text-slate-300'}`}>
                    🛵 Local Plan (Local Subcontract / Daily Run)
                  </h3>
                  {!isTripActive && (
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-900/80 text-cyan-300 border border-cyan-700">
                      ACTIVE PLAN
                    </span>
                  )}
                </div>
                <p className="text-xs text-slate-400 mt-0.5">
                  City & local industrial cluster vendors for daily transport rounds
                </p>
                <div className="flex items-center gap-3 mt-2 text-xs font-mono">
                  <span className="text-cyan-300 font-semibold">
                    {logisticsPlan?.local_plan?.total_outward_items || 0} to Send ({logisticsPlan?.local_plan?.total_outward_qty || 0} pcs)
                  </span>
                  <span className="text-slate-600">•</span>
                  <span className="text-amber-300 font-semibold">
                    {logisticsPlan?.local_plan?.total_inward_items || 0} to Collect ({logisticsPlan?.local_plan?.total_inward_qty || 0} pcs)
                  </span>
                </div>
              </div>
            </div>
            <div className="text-right shrink-0">
              <span className="text-xs font-mono font-bold text-cyan-400 bg-cyan-950 px-2 py-1 rounded border border-cyan-800">
                {logisticsPlan?.local_plan?.total_outward_weight_kg || 0} KG
              </span>
            </div>
          </button>
        </div>

        {/* ─── Active Plan Details: Outward Dispatches & Inward Pickups ─── */}
        <div className="space-y-5 pt-2">
          
          {/* Sub-Section A: OUTWARD DISPATCHES (To Load & Send to Vendors) */}
          <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-850 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="p-1 rounded bg-indigo-950 text-indigo-400 border border-indigo-800">
                  <ArrowUpRight className="w-3.5 h-3.5" />
                </span>
                <h4 className="text-xs font-bold uppercase text-white tracking-wider">
                  1. Outward Dispatches to {isTripActive ? 'Trip' : 'Local'} Vendors ({currentPlan?.total_outward_items || 0} Items • {currentPlan?.total_outward_qty || 0} pcs)
                </h4>
              </div>
              <span className="text-xs font-mono text-slate-400">
                Total Est Weight: <strong className="text-cyan-300">{currentPlan?.total_outward_weight_kg || 0} kg</strong>
              </span>
            </div>

            {(!currentPlan?.outward_dispatches || currentPlan.outward_dispatches.length === 0) ? (
              <div className="p-4 rounded-lg bg-slate-900/50 text-center text-xs text-slate-500">
                No in-house batches currently staged for {isTripActive ? 'Trip' : 'Local'} vendor dispatch.
              </div>
            ) : (
              <div className="space-y-2.5">
                {currentPlan.outward_dispatches.map((item, idx) => (
                  <div
                    key={`out-${item.batch_id}-${idx}`}
                    className="p-3 rounded-lg bg-slate-900 border border-slate-800/80 hover:border-slate-700 flex flex-col md:flex-row md:items-center justify-between gap-3 transition-all"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-xs font-bold text-cyan-400 bg-cyan-950 px-2 py-0.5 rounded border border-cyan-800">
                          {item.item_code}
                        </span>
                        <span className="text-xs font-bold text-white">{item.item_name}</span>
                        {item.is_critical ? (
                          <span className="px-1.5 py-0.5 rounded bg-red-950 text-red-300 border border-red-600 text-[10px] font-bold">
                            CRITICAL
                          </span>
                        ) : null}
                      </div>

                      <div className="text-xs text-slate-400 flex flex-wrap items-center gap-x-4 gap-y-1">
                        <span>Completed: <strong className="text-slate-300">{item.completed_process}</strong></span>
                        <span className="flex items-center gap-1 text-cyan-300 font-semibold">
                          <ArrowRight className="w-3 h-3 text-cyan-400" />
                          <span>Next: {item.next_process || 'Outsourced Process'}</span>
                        </span>
                        <span>Destination: <strong className="text-amber-300">{item.destination_vendor_name || 'Assigned Vendor'}</strong></span>
                        <span>Quantity: <strong className="text-white font-mono">{item.quantity} pcs</strong></span>
                        {item.total_weight_kg > 0 && (
                          <span>Weight: <strong className="text-slate-200 font-mono">{item.total_weight_kg} kg</strong></span>
                        )}
                      </div>

                      {item.destination_vendor_phone && (
                        <div className="text-[11px] text-slate-500 flex items-center gap-2">
                          <PhoneCall className="w-3 h-3 text-slate-500" />
                          <span>{item.destination_vendor_phone}</span>
                          {item.destination_vendor_address && (
                            <>
                              <span>•</span>
                              <span className="truncate max-w-sm">{item.destination_vendor_address}</span>
                            </>
                          )}
                        </div>
                      )}
                    </div>

                    <button
                      onClick={onOpenBulkDispatch}
                      className="px-3 py-1.5 rounded-lg bg-indigo-600/80 hover:bg-indigo-600 text-white text-xs font-semibold self-start md:self-auto shrink-0 transition-colors"
                    >
                      Dispatch Now
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Sub-Section B: INWARD MATERIAL COLLECTIONS (From Vendors) */}
          <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-850 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="p-1 rounded bg-amber-950 text-amber-400 border border-amber-800">
                  <ArrowDownLeft className="w-3.5 h-3.5" />
                </span>
                <h4 className="text-xs font-bold uppercase text-white tracking-wider">
                  2. Inward Material Collections from {isTripActive ? 'Trip' : 'Local'} Vendors ({currentPlan?.total_inward_items || 0} Items • {currentPlan?.total_inward_qty || 0} pcs)
                </h4>
              </div>
              <span className="text-xs font-mono text-slate-400">
                Total Est Weight: <strong className="text-amber-300">{currentPlan?.total_inward_weight_kg || 0} kg</strong>
              </span>
            </div>

            {(!currentPlan?.inward_pickups || currentPlan.inward_pickups.length === 0) ? (
              <div className="p-4 rounded-lg bg-slate-900/50 text-center text-xs text-slate-500">
                No materials currently expected for arrival or collection from {isTripActive ? 'Trip' : 'Local'} vendors on {planDate}.
              </div>
            ) : (
              <div className="space-y-2.5">
                {currentPlan.inward_pickups.map((item, idx) => (
                  <div
                    key={`in-${item.batch_id}-${idx}`}
                    className="p-3 rounded-lg bg-slate-900 border border-slate-800/80 hover:border-slate-700 flex flex-col md:flex-row md:items-center justify-between gap-3 transition-all"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-xs font-bold text-cyan-400 bg-cyan-950 px-2 py-0.5 rounded border border-cyan-800">
                          {item.item_code}
                        </span>
                        <span className="text-xs font-bold text-white">{item.item_name}</span>
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          item.lead_status?.is_overdue
                            ? 'bg-red-950 text-red-300 border border-red-600'
                            : 'bg-amber-950 text-amber-300 border border-amber-600'
                        }`}>
                          {item.lead_status?.badge || 'SCHEDULED'}
                        </span>
                      </div>

                      <div className="text-xs text-slate-400 flex flex-wrap items-center gap-x-4 gap-y-1">
                        <span>Process: <strong className="text-white">{item.current_process}</strong></span>
                        <span>Vendor: <strong className="text-amber-300">{item.vendor_name}</strong></span>
                        <span>Quantity: <strong className="text-white font-mono">{item.quantity} pcs</strong></span>
                        {item.total_weight_kg > 0 && (
                          <span>Weight: <strong className="text-slate-200 font-mono">{item.total_weight_kg} kg</strong></span>
                        )}
                        {item.challan_no && (
                          <span>DC: <code className="text-cyan-400 font-mono">{item.challan_no}</code></span>
                        )}
                        <span>Due: <strong className="text-slate-200 font-mono">{item.expected_delivery_date || 'N/A'}</strong></span>
                      </div>

                      {item.vendor_phone && (
                        <div className="text-[11px] text-slate-500 flex items-center gap-2">
                          <PhoneCall className="w-3 h-3 text-slate-500" />
                          <span>{item.contact_person || 'Contact'}: {item.vendor_phone}</span>
                        </div>
                      )}
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        onClick={() => onOpenFollowup(item)}
                        className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-amber-300 text-xs font-semibold flex items-center gap-1.5 border border-slate-700 transition-colors"
                      >
                        <PhoneCall className="w-3 h-3" />
                        <span>Call Vendor</span>
                      </button>
                      <button
                        onClick={() => onAdvanceStage(item)}
                        className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-sm transition-colors"
                      >
                        <CheckCircle2 className="w-3 h-3" />
                        <span>Receive Material</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

        </div>

      </div>


      {/* ─── STANDARD PRIORITY FOLLOW-UP SECTIONS ─────────────────────────── */}
      
      {/* Section 1: URGENT OVERDUE ITEMS FROM VENDORS */}
      <div className="bg-slate-900 border border-red-900/40 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-sm font-bold text-red-400 flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-red-400" />
            <span>Overdue Vendor Deliveries ({overdue.length} Overdue)</span>
          </h3>
          <span className="text-xs text-slate-400">Committed lead time exceeded</span>
        </div>

        {overdue.length === 0 ? (
          <div className="p-4 bg-slate-950 rounded-lg text-center text-xs text-slate-500">
            No overdue deliveries at external vendors. All subcontract jobs on schedule!
          </div>
        ) : (
          <div className="space-y-3">
            {overdue.map(t => (
              <div 
                key={t.id}
                className="bg-slate-950 border border-red-500/40 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-md"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <span className="font-mono text-sm font-bold text-cyan-400 bg-cyan-950/80 px-2 py-0.5 rounded border border-cyan-800">
                      {t.item_code}
                    </span>
                    <span className="text-sm font-bold text-white">{t.item_name}</span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase border ${
                      t.vendor_type === 'Trip'
                        ? 'bg-amber-950 text-amber-300 border-amber-600'
                        : 'bg-cyan-950 text-cyan-300 border-cyan-700'
                    }`}>
                      {t.vendor_type === 'Trip' ? '🚚 Trip' : '🛵 Local'}
                    </span>
                    {t.is_critical && (
                      <span className="px-2 py-0.5 rounded bg-red-950 text-red-300 border border-red-600 text-[10px] font-bold">
                        CRITICAL
                      </span>
                    )}
                  </div>
                  
                  <div className="text-xs text-slate-300 flex flex-wrap items-center gap-x-4 gap-y-1">
                    <span>Process: <strong className="text-white">{t.current_process}</strong></span>
                    <span>Vendor: <strong className="text-amber-300">{t.vendor_name}</strong></span>
                    <span>Quantity: <strong className="text-white font-mono">{t.quantity} pcs</strong></span>
                    {t.challan_no && <span>DC: <code className="text-cyan-400">{t.challan_no}</code></span>}
                  </div>

                  <div className="text-xs flex items-center gap-2 text-slate-400">
                    <span>Committed Date: <strong className="text-slate-200">{t.expected_delivery_date}</strong></span>
                    <span>•</span>
                    <span className="text-red-400 font-bold">{t.lead_status?.badge}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => onOpenFollowup(t)}
                    className="px-3.5 py-1.5 rounded-lg bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md shadow-amber-600/20"
                  >
                    <PhoneCall className="w-3.5 h-3.5" />
                    <span>Call Vendor</span>
                  </button>

                  <button
                    onClick={() => onAdvanceStage(t)}
                    className="px-3.5 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md shadow-cyan-600/20"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Receive / Move</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Section 2: DUE TODAY ITEMS */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-sm font-bold text-amber-300 flex items-center gap-2">
            <Clock className="w-4 h-4 text-amber-400" />
            <span>Deliveries Due Today ({dueToday.length} Expected)</span>
          </h3>
          <span className="text-xs text-slate-400">Scheduled for delivery completion today</span>
        </div>

        {dueToday.length === 0 ? (
          <div className="p-4 bg-slate-950 rounded-lg text-center text-xs text-slate-500">
            No items scheduled to arrive from vendors today.
          </div>
        ) : (
          <div className="space-y-3">
            {dueToday.map(t => (
              <div 
                key={t.id}
                className="bg-slate-950 border border-amber-600/40 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"
              >
                <div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-sm font-bold text-cyan-400">{t.item_code}</span>
                    <span className="text-sm font-bold text-white">{t.item_name}</span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase border ${
                      t.vendor_type === 'Trip'
                        ? 'bg-amber-950 text-amber-300 border-amber-600'
                        : 'bg-cyan-950 text-cyan-300 border-cyan-700'
                    }`}>
                      {t.vendor_type === 'Trip' ? '🚚 Trip' : '🛵 Local'}
                    </span>
                    <span className="px-2 py-0.5 rounded bg-amber-950 text-amber-300 border border-amber-600 text-[10px] font-bold">
                      DUE TODAY
                    </span>
                  </div>
                  <div className="text-xs text-slate-400 mt-1">
                    Process: <span className="text-white font-medium">{t.current_process}</span> at <span className="text-amber-300 font-medium">{t.vendor_name}</span> ({t.quantity} pcs)
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => onOpenFollowup(t)}
                    className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-amber-400 text-xs font-medium border border-slate-700"
                  >
                    Check Status
                  </button>
                  <button
                    onClick={() => onAdvanceStage(t)}
                    className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-medium"
                  >
                    Receive Material
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Section 3: RECENT VENDOR CALL & COMMUNICATION LOGS */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <PhoneCall className="w-4 h-4 text-indigo-400" />
          <span>Recent Vendor Follow-up Logs</span>
        </h3>

        {recentFollowups.length === 0 ? (
          <div className="p-4 bg-slate-950 rounded-lg text-center text-xs text-slate-500">
            No recent calls logged.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {recentFollowups.map(log => (
              <div key={log.id} className="p-3 bg-slate-950 rounded-lg border border-slate-800 text-xs space-y-1">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-cyan-400">{log.item_code}</span>
                    <span className="text-slate-300 font-medium">{log.vendor_name}</span>
                    <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold uppercase ${
                      log.vendor_type === 'Trip' ? 'bg-amber-950 text-amber-300' : 'bg-cyan-950 text-cyan-300'
                    }`}>
                      {log.vendor_type === 'Trip' ? 'Trip' : 'Local'}
                    </span>
                    <span className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 text-[10px]">{log.method}</span>
                  </div>
                  <span className="text-slate-500 text-[10px]">{log.date_contacted}</span>
                </div>
                <p className="text-slate-200 mt-1">"{log.vendor_status_update}"</p>
                {log.promised_date && (
                  <span className="inline-block text-cyan-300 font-mono text-[10px] bg-cyan-950 px-2 py-0.5 rounded border border-cyan-800/40">
                    Promised Dispatch: {log.promised_date}
                  </span>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
